---
name: Build
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - 2.1.x
  pull_request:
jobs:
  build:
    uses: dropwizard/workflows/.github/workflows/maven.yml@main
    secrets: inherit
